require('common');

local settings = T{ };
settings["background"] = T{ };
settings["mobs"] = T{ };
settings["mobs"]["Woh Gates"] = T{ };
settings["mobs"]["Woh Gates"][344] = T{ };
settings["mobs"]["Woh Gates"][345] = T{ };
settings["mobs"]["Woh Gates"][346] = T{ };
settings["font_height"] = 12;
settings["call"] = false;
settings["callnumber"] = "4";
settings["red"] = "|cFFFF0000|";
settings["background"]["visible"] = true;
settings["background"]["color"] = 4278190080;
settings["color"] = 4294967295;
settings["font_family"] = "Arial";
settings["yellow"] = "|cFFFFFF00|";
settings["green"] = "|cFF00FF00|";
settings["position_x"] = 500;
settings["visible"] = false;
settings["position_y"] = 500;
settings["mobs"]["Woh Gates"][344][1] = "Apex Jagil";
settings["mobs"]["Woh Gates"][344][2] = true;
settings["mobs"]["Woh Gates"][344][3] = 51;
settings["mobs"]["Woh Gates"][344][4] = 0;
settings["mobs"]["Woh Gates"][344][5] = true;
settings["mobs"]["Woh Gates"][345][1] = "Apex Jagil";
settings["mobs"]["Woh Gates"][345][2] = true;
settings["mobs"]["Woh Gates"][345][3] = 51;
settings["mobs"]["Woh Gates"][345][4] = 0;
settings["mobs"]["Woh Gates"][345][5] = true;
settings["mobs"]["Woh Gates"][346][1] = "Apex Jagil";
settings["mobs"]["Woh Gates"][346][2] = true;
settings["mobs"]["Woh Gates"][346][3] = 51;
settings["mobs"]["Woh Gates"][346][4] = 0;
settings["mobs"]["Woh Gates"][346][5] = true;

return settings;
