require('common');

local settings = T{ };
settings["background"] = T{ };
settings["mobs"] = T{ };
settings["mobs"]["Outer Ra'Kaznar [U1]"] = T{ };
settings["mobs"]["Outer Ra'Kaznar [U1]"][201] = T{ };
settings["mobs"]["Outer Ra'Kaznar [U1]"][122] = T{ };
settings["mobs"]["Outer Ra'Kaznar [U1]"][263] = T{ };
settings["font_height"] = 12;
settings["call"] = false;
settings["callnumber"] = "4";
settings["visible"] = true;
settings["background"]["visible"] = true;
settings["background"]["color"] = 4278190080;
settings["color"] = 4294967295;
settings["font_family"] = "Arial";
settings["yellow"] = "|cFFFFFF00|";
settings["green"] = "|cFF00FF00|";
settings["position_x"] = 500;
settings["red"] = "|cFFFF0000|";
settings["position_y"] = 500;
settings["mobs"]["Outer Ra'Kaznar [U1]"][201][1] = "Biune Porxie";
settings["mobs"]["Outer Ra'Kaznar [U1]"][201][2] = false;
settings["mobs"]["Outer Ra'Kaznar [U1]"][201][3] = -1;
settings["mobs"]["Outer Ra'Kaznar [U1]"][201][4] = -1;
settings["mobs"]["Outer Ra'Kaznar [U1]"][201][5] = true;
settings["mobs"]["Outer Ra'Kaznar [U1]"][201][6] = 0;
settings["mobs"]["Outer Ra'Kaznar [U1]"][122][1] = "Abject Obdella";
settings["mobs"]["Outer Ra'Kaznar [U1]"][122][2] = false;
settings["mobs"]["Outer Ra'Kaznar [U1]"][122][3] = -1;
settings["mobs"]["Outer Ra'Kaznar [U1]"][122][4] = -1;
settings["mobs"]["Outer Ra'Kaznar [U1]"][122][5] = true;
settings["mobs"]["Outer Ra'Kaznar [U1]"][122][6] = 0;
settings["mobs"]["Outer Ra'Kaznar [U1]"][263][1] = "Cachaemic Bhoot";
settings["mobs"]["Outer Ra'Kaznar [U1]"][263][2] = false;
settings["mobs"]["Outer Ra'Kaznar [U1]"][263][3] = -1;
settings["mobs"]["Outer Ra'Kaznar [U1]"][263][4] = -1;
settings["mobs"]["Outer Ra'Kaznar [U1]"][263][5] = true;
settings["mobs"]["Outer Ra'Kaznar [U1]"][263][6] = 0;

return settings;
