require('common');

local settings = T{ };
settings["visibleJob"] = T{ };
settings["background"] = T{ };
settings["deadColor"] = "|cFFFF0000|";
settings["visibleJob"][1] = true;
settings["visibleJob"][2] = true;
settings["visibleJob"][3] = true;
settings["visibleJob"][4] = true;
settings["visibleJob"][5] = true;
settings["visibleJob"][6] = true;
settings["visibleJob"][7] = true;
settings["visibleJob"][8] = true;
settings["visibleJob"][9] = false;
settings["visibleJob"][10] = true;
settings["visibleJob"][11] = true;
settings["visibleJob"][12] = true;
settings["visibleJob"][13] = true;
settings["visibleJob"][14] = true;
settings["visibleJob"][15] = true;
settings["visibleJob"][16] = false;
settings["visibleJob"][17] = false;
settings["visibleJob"][18] = false;
settings["visibleJob"][19] = true;
settings["visibleJob"][20] = true;
settings["visibleJob"][21] = true;
settings["visibleJob"][22] = true;
settings["color"] = 4294967295;
settings["red"] = "|cFFFF0000|";
settings["background"]["visible"] = true;
settings["background"]["color"] = 4278190080;
settings["font_height"] = 12;
settings["mobcolor"] = "|cFFFFFFFF|";
settings["visible"] = true;
settings["position_x"] = 500;
settings["fightColor"] = "|cFFFFFF00|";
settings["green"] = "|cFF00FF00|";
settings["yellow"] = "|cFFFFFF00|";
settings["font_family"] = "Arial";
settings["position_y"] = 500;
settings["displayTime"] = 15;

return settings;
